### ISSUE TITLE
A failed update prevents further update attempts because "IV is already up to date"

### ISSUE THREAD

**Issue by mas1701** [tmiland/invidious-installer#11]
If anything goes wrong during an Invidious Update run, after pulling a fresh version from Git, a second attempt is not possible unless the Git sources get updated again.

This seems to be because the Invidious Installer only checks for Git changes, not for the success of the last update run.

Maybe we could have a "force update" option or an improved check, if the last update was really applied correctly?

(As a workaround, I temporarily changed an "if" statement so the script believed the sources had changed. It worked.)

**Comment by tmiland** [comment]
Hello. 

> If anything goes wrong during an Invidious Update run, after pulling a fresh version from Git, a second attempt is not possible unless the Git sources get updated again.

i see no reason to pull a new version if a fresh version is already pulled,
so this is the expected behavior.
