### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ArminEskandarii** [tmiland/invidious-installer#7]
Hi. I installed invidious on my Ubuntu server and it gave me this address "http://localhost:3000/" but it is not working. what should I do?
Note: I dont have a domain. is it possible to run invidious only with the server?

**Comment by R0GGER** [comment]
https://github.com/tmiland/invidious-installer/pull/10

**Comment by tmiland** [comment]
> Hi. I installed invidious on my Ubuntu server and it gave me this address "[http://localhost:3000](http://localhost:3000/)" but it is not working. what should I do? Note: I dont have a domain. is it possible to run invidious only with the server?

Hello,
I need the install log please, so i can see what's going on.

**Comment by R0GGER** [comment]
Ehh.... an assumption. He's using a server not his computer... He can't connect to localhost when Invidious isn't installed on his localhost. 
Logic? Sort of...

**Comment by tmiland** [comment]
Have a look on the [index of this repo](https://github.com/tmiland/invidious-installer#install-with-default-options-to-run-on-localhost) for options:

![Screenshot 2023-12-23 at 13-57-06 tmiland_invidious-installer Automatic install script for Invidious](https://github.com/tmiland/invidious-installer/assets/1203834/389e0a47-4e5a-4be5-8b51-878b4f9bbfdb)

Replace localhost with local or public IP of the server (depending on your firewall), if used without domain or https (reverse proxy)

**Comment by R0GGER** [comment]
Ah… sorry! Haven’t scrolled down. 🤐
