### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by ddscentral** [tmiland/invidious-installer#9]
Invidious can be built and used on ARM64 boards like Raspberry Pi 4 and 5. But your script only supports amd64.
From what I understand this is because you rely on OpenSUSE repositories for crystal and they only host packages for amd64.

There are other repositories which host crystal packages, such as this one provided by 84codes which includes both amd64 and arm64 builds.
https://packagecloud.io/84codes/crystal

If I manually install crystal on an arm64 machine, your installer works just fine (with the arch check commented out, of course).
It would be beneficial to if not change to a different repository, then at least add a workaround in the documentation for those who want to use your script on machines other than amd64.

**Comment by tmiland** [comment]
Hello,
support for boards like Raspberry Pi/ARM64 has been excluded because i have no way to test these boards/arches.

I'm using virtualized amd64, and what is included is what i have been able to test.

That means, to add support for Raspberry Pi/ARM64, someone has to test it and open a pull request with the changes.

Regards.

**Comment by ddscentral** [comment]
Understood. 
That is certainly within my capabilities.
So far, I tried new installs on Debian Bookworm on a Pi 5 (stock Debian in a KVM, not the Pi flavor) and on Ubuntu in a KVM on a Pi 4. Both worked fine with crystal build from the 84codes repo with no other changes needed. Invidious runs fine.
For other distros, I do have the hardware, I could spin-up ARM64 VMs with different distros which you support to test your script.
Just need to know which distros I should test on. Would one from each distro group be enough ?

**Comment by tmiland** [comment]
> Would one from each distro group be enough ?

I would guess so.
